# UpVote API Verification Script
# This script automates the testing workflow for UpVote APIs.

$BaseUrl = "http://localhost:3000"
$Email = "admin@test.com"
$Password = "securepassword123"
$CompanyName = "Test Automation Corp"

Write-Host "--- starting UpVote API Verification ---" -ForegroundColor Cyan

# 1. Sign Up
Write-Host "[1/7] Creating Company Account..." -NoNewline
$SignupBody = @{
    name = $CompanyName
    email = $Email
    password = $Password
} | ConvertTo-Json

try {
    $SignupResponse = Invoke-RestMethod -Uri "$BaseUrl/api/auth/signup" -Method Post -Body $SignupBody -ContentType "application/json"
    $CompanyId = $SignupResponse.company.id
    Write-Host " SUCCESS ($CompanyId)" -ForegroundColor Green
} catch {
    if ($_.Exception.Message -match "400") {
        Write-Host " SKIPPED (Already exists)" -ForegroundColor Yellow
    } else {
        Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
        return
    }
}

# 2. Login (Note: NextAuth requires browser-based login for sessions)
Write-Host "[2/7] Skipping REST Login (NextAuth managed)..." -ForegroundColor Yellow
$Session = New-Object Microsoft.PowerShell.Commands.WebRequestSession

# 3. Create Application context for testing
$AppId = "app_test_123"
Write-Host "[3/7] Application context: $AppId" -ForegroundColor Gray

# 4. Submit Feedback
Write-Host "[4/7] Submitting Feedback..." -NoNewline
$FeedbackBody = @{
    applicationId = $AppId
    userId = "tester_001"
    title = "Automated Test Feedback"
    description = "Generated by PowerShell verify-api script"
} | ConvertTo-Json

try {
    $FeedbackResponse = Invoke-RestMethod -Uri "$BaseUrl/api/widget/feedback" -Method Post -Body $FeedbackBody -ContentType "application/json"
    $FeedbackId = $FeedbackResponse.feedback.id
    Write-Host " SUCCESS ($FeedbackId)" -ForegroundColor Green
} catch {
    Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
    return
}

# 5. Vote
Write-Host "[5/7] Casting Upvote..." -NoNewline
$VoteBody = @{
    applicationId = $AppId
    feedbackId = $FeedbackId
    userId = "tester_001"
    voteType = "UPVOTE"
} | ConvertTo-Json

try {
    $VoteResponse = Invoke-RestMethod -Uri "$BaseUrl/api/widget/vote" -Method Post -Body $VoteBody -ContentType "application/json"
    Write-Host " SUCCESS (Count: $($VoteResponse.voteCount))" -ForegroundColor Green
} catch {
    Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
    return
}

# 6. Fetch Analytics
Write-Host "[6/7] Fetching Analytics..." -NoNewline
try {
    $AnalyticsResponse = Invoke-RestMethod -Uri "$BaseUrl/api/dashboard/analytics?applicationId=$AppId" -Method Get -WebSession $Session
    Write-Host " SUCCESS (Total: $($AnalyticsResponse.totalFeedback))" -ForegroundColor Green
} catch {
    Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

# 7. Check Users
Write-Host "[7/7] Checking User Activity..." -NoNewline
try {
    $UsersResponse = Invoke-RestMethod -Uri "$BaseUrl/api/dashboard/users?applicationId=$AppId" -Method Get -WebSession $Session
    Write-Host " SUCCESS (Users: $($UsersResponse.users.Count))" -ForegroundColor Green
} catch {
    Write-Host " FAILED: $($_.Exception.Message)" -ForegroundColor Red
}

Write-Host "--- Verification Complete ---" -ForegroundColor Cyan
Write-Host "Note: Ensure 'npm run dev' is running in another terminal." -ForegroundColor DarkGray
